package com.ahmadZufarJsmartMH.model;

public enum ProductCategory
{
    BOOK, KITCHEN, ELECTRONIC, FASHION, GAMING, GADGET, MOTHERCARE, COSMETICS, HEALTCARE, FURNITURE, JEWELRY, TOYS, FNB, STATIONERY, SPORTS, AUTOMOTIVE, PETCARE, ART_CRAFT, CARPENTRY, MISCELLANEOUS, PROPERTY, TRAVEL, WEDDING
}
